### ISSUE TITLE
(NOT) MALWARE!!!!!

### ISSUE THREAD

**Issue by sigmaenigma** [blackbricksoftware/Chrome-Autologin#1]
<h1>This is Malyare!!!</h1> Be careful when downloading this.

**Comment by davidjosephhayes** [comment]
<h1>I am Dave, king of the a Poopy Headz</h1>\* Myahhhhh1
- Me2
  - Hehehehe 2a
  - Lordinggg 2b

**Comment by sigmaenigma** [comment]
<h1>Can Confirm</h1>  yo <h2>sup</h2>

**Comment by davidjosephhayes** [comment]
LOL you guys can edit my comments?

**Comment by davidjosephhayes** [comment]
I didn't know that.

**Comment by sigmaenigma** [comment]
~Is this fixed yet?~

# YOU ARE GREAT! @davidjosephhayes <3 <3

**Comment by davidjosephhayes** [comment]
Why thank you @sigmaenigma! You are the best. I will give 100 Bitcoin you

**Comment by sigmaenigma** [comment]
Thanks man. Just drop it in my wallet

**Comment by davidjosephhayes** [comment]
What's you address?

**Comment by sigmaenigma** [comment]
Nexo Wallet for BTC: 355mcXNBHbqtWfZfd34iBVPSPfQesqMDst

**Comment by davidjosephhayes** [comment]
Sir you are poor: https://www.blockchain.com/btc/address/355mcXNBHbqtWfZfd34iBVPSPfQesqMDst

**Comment by sigmaenigma** [comment]
For now

**Comment by sigmaenigma** [comment]
Great thank you
